title: Shruthip Venkatesh
description: A portfolio of myself
theme: just-the-docs

url: https://shruthipv96.github.io/portfolio

aux_links:
  Template Repository: https://github.com/shruthipv96/portfolio3

permalink: pretty

logo: "/assets/images/Shruthip_Passport_Size_Photo.jpg"

favicon_ico: "/assets/images/S-V.ico"
