title: Shruthip Venkatesh
description: A portfolio of myself
theme: just-the-docs

url: https://shruthipv96.github.io/portfolio

permalink: pretty

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

back_to_top: true
back_to_top_text: "Back to top"
